### ISSUE TITLE
AttributeError: module 'streamlit.components.v1' has no attribute 'components'

### ISSUE THREAD

**Issue by WaldekGizynski** [PablocFonseca/streamlit-aggrid#275]
I use Aggrid on the site along with st.tabs. After upgrading streamlit to 1.34, an error started to occur. 
When the page uses st.tabs and there is a table on one of the tabs and a st.form with st.file_uploader which I reload several times, then I get this error:
    ```
selection = AgGrid(
  File "C:\Users\C-WG001\Repositories\ng-datatool-streamlit\venv\lib\site-packages\st_aggrid\__init__.py", line 396, in AgGrid
    except components.components.MarshallComponentException as ex:
AttributeError: module 'streamlit.components.v1' has no attribute 'components'
```
I can't figure out what needs to be met for the error to be easily reproduced. However, I know that the error started to appear since the streamlit upgrade. 
The error occurs for aggrid 0.3.5 and 1.0.5 for streamlit 1.34, also 1.35.
I found a somewhat similar topic regarding streamlit changes here: https://github.com/streamlit/streamlit/issues/8644
I checked streamlit 1.32 and actually the error does not occur.
Maybe based on this, it will be possible to determine what is the cause and solve the problem.

Translated with DeepL.com (free version)

**Comment by MarkusSagen** [comment]
Issue is mitigated when moving to version `1.32`

**Comment by danialcheung** [comment]
I've proposed a simple PR for this [here](https://github.com/PablocFonseca/streamlit-aggrid/pull/280).

**Comment by matthalstead-mfe** [comment]
Would be good news to have this PR accepted.

**Comment by JohnnyDev818** [comment]
Bumping this up.  I am having the same issue as the original poster.  Very intermittent and difficult to reproduce.  I am using Streamlit 1.38 and I can't go back to 1.32.  

Will bribe with lots of coffee's :-).

**Comment by danialcheung** [comment]
For anyone still experiencing this error, it's due to Streamlit renaming their module from [components.py](https://github.com/streamlit/streamlit/blob/1.32.0/lib/streamlit/components/v1/components.py) to [custom_component.py](https://github.com/streamlit/streamlit/blob/develop/lib/streamlit/components/v1/custom_component.py). 

The solution is a two-line fix within [`st_aggrid/__init__.py`](https://github.com/PablocFonseca/streamlit-aggrid/blob/main/st_aggrid/__init__.py) you can do yourself.

Simply replace the two instances of `components.components.MarshallComponentException` with `components.custom_component.MarshallComponentException` at lines [`348`](https://github.com/PablocFonseca/streamlit-aggrid/blob/5b4c7d88af1bec64154c6debedfca0f0b0624255/st_aggrid/__init__.py#L348) and [`352`](https://github.com/PablocFonseca/streamlit-aggrid/blob/5b4c7d88af1bec64154c6debedfca0f0b0624255/st_aggrid/__init__.py#L352). 

You can view the details of this in the [PR](https://github.com/PablocFonseca/streamlit-aggrid/pull/280) I've submitted, but I don't think it'll be accepted any time soon. 

I hope this manages to fix things!
